version: "3.5"

services:
  duniter-v2s-gecko-tests:
    container_name: duniter-v2s-gecko-tests
    image: duniter/duniter-v2s:debug-latest
    command: --sealing=manual
    ports:
      - "127.0.0.1:9615:9615"
      - "127.0.0.1:9933:9933"
      - "0.0.0.0:9944:9944"
      - "30333:30333"
    environment:
      DUNITER_INSTANCE_NAME: "gecko_tests"
      DUNITER_CHAIN_NAME: "dev"
      DUNITER_GENESIS_CONFIG: "/var/lib/duniter/gecko_tests.json"
    volumes:
      - ./data:/var/lib/duniter
