stages:
  - format
  - build_and_test
  - quality

.env:
  image: axiomteam/gecko-ci:v0.0.5
  tags:
    - redshift
  before_script:
    - rustup show
    - rustc --version && cargo --version

format:
  extends: .env
  stage: format
  script:
    - cargo fmt -- --version
    - cargo fmt -- --check
    - flutter format --set-exit-if-changed lib packages/dubp_rs/lib/dubp.dart
        
build_and_test:
  extends: .env
  stage: build_and_test
  tags:
    - redshift
  script: 
    - RUSTFLAGS="-D warnings" cargo make
    - cd packages/dubp_rs && flutter pub get && cd ../..
    - flutter analyze
    - cargo test
    # - flutter test

lint:
  extends: .env
  stage: quality
  script:
    - cargo clippy -- -V
    - cargo clippy --all --tests -- -D warnings --verbose
    
audit_dependencies:
  extends: .env
  stage: quality
  script:
    - cargo deny -V
    - cargo deny check
