schema:
  - ../durt2/lib/src/models/graphql/squid/squid-schema.graphql
documents:
  - ../durt2/lib/src/models/graphql/**/*.graphql
  - ../durt2/lib/src/models/graphql/**/*.gql
extensions:
  endpoints:
    default:
      url: 'https://gtest-squid.axiom-team.fr/v1beta1/relay' 