name: gecko
description: Pay with G1.
publish_to: "none"

version: 0.1.27+108

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  bubble: ^1.2.1
  carousel_slider: ^5.0.0
  graphql_flutter: ^5.2.0-beta.8
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  jdenticon_dart: ^2.0.0
  logger: ^2.5.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.0+1
  pin_code_fields: ^8.0.1
  printing: ^5.14.2
  provider: ^6.1.2
  barcode_scan2: ^4.5.0
  qr_flutter: ^4.1.0
  responsive_framework: ^1.5.1
  sentry_flutter: ^8.14.0
  truncate: ^3.0.1
  unorm_dart: ^0.3.0
  dio: ^5.8.0+1
  durt: ^0.1.9
  package_info_plus: ^8.2.1
  polkawallet_sdk: #^0.5.2
    # path: ../substrate_sdk
    git:
      url: https://github.com/poka-IT/sdk.git
      # ref: gecko-fixes-4
      ref: 0d26bb58618e0d60d4fbe36e1e406ea67ff9c077
  dots_indicator: ^4.0.1
  connectivity_plus: ^6.1.3
  image_cropper: ^9.0.0
  easy_localization: ^3.0.7+1
  flutter_markdown: ^0.7.6+2
  pointycastle: ^3.9.1
  hex: ^0.2.0
  accordion: ^2.6.0
  flutter_svg: ^2.0.17
  pinenacl: ^0.6.0
  fast_base58: ^0.2.1
  tutorial_coach_mark: ^1.2.12
  confetti: ^0.8.0
  url_launcher: ^6.3.1
  crypto: ^3.0.6
  screen_brightness: ^2.1.1
  uuid: ^4.5.1
  fade_and_translate: ^0.1.3
  markdown: ^7.3.0
  http: ^1.3.0
  flutter_launcher_icons: ^0.14.3
  gif_view: ^1.0.2

  # polkadart
  polkadart: ^0.6.1
  polkadart_cli: ^0.6.1

  # durt2:
  #   path: ../../durt2
    # git:
    #   url: https://git.duniter.org/libs/durt2

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  icons_launcher: ^3.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/icon/gecko_flat.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/icon/gecko_flat_background.png"
  remove_alpha_ios: true
  adaptive_icon_background: "transparent"
  adaptive_icon_foreground: "assets/icon/gecko_flat.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
  linux:
    generate: false

uses-material-design: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - config/
    - assets/
    - assets/translations/
    - assets/home/
    - assets/avatars/
    - assets/chests/
    - assets/icon/
    - assets/onBoarding/
    - assets/onBoarding/progress_bar/
    - assets/walletOptions/
    - sounds/

polkadart:
  output_dir: lib/generated
  chains:
    gdev: wss://gdev.p2p.legal/ws
