name: gecko
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dubp:
    path: packages/dubp_rs
  flutter_launcher_icons: "^0.8.0"
  qrscan: ^0.2.21
  permission_handler:
  image_gallery_saver:
  image_picker:
  graphql_flutter: ^4.0.0-beta.6 #^3.1.0
  provider: ^4.3.2+3
  truncate: ^2.1.2
  sentry_flutter: ^4.0.1
  path_provider: ^1.6.24
  pin_code_fields: ^6.0.2


flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/gecko5bduniter2.png"
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - images/
