name: gecko
description: Pay with G1.
publish_to: "none"

version: 0.1.23+101

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  bubble: ^1.2.1
  carousel_slider: ^5.0.0
  graphql_flutter: ^5.2.0-beta.8
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  jdenticon_dart: ^2.0.0
  logger: ^2.5.0
  path_provider: ^2.1.5
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  printing: ^5.13.4
  provider: ^6.1.2
  barcode_scan2: ^4.3.3
  qr_flutter: ^4.1.0
  responsive_framework: ^1.5.1
  sentry_flutter: ^8.12.0
  truncate: ^3.0.1
  unorm_dart: ^0.3.0
  dio: ^5.7.0
  durt: ^0.1.9
  package_info_plus: ^8.1.2
  polkawallet_sdk: #^0.5.2
    # path: ../substrate_sdk
    git:
    #   # url: https://github.com/polkawallet-io/sdk.git
    #   # ref: develop
      url: https://github.com/poka-IT/sdk.git
    #   # ref: gecko-fixes-4
      ref: 04ebfd0af1781d336126498534e3b656355d5927
  dots_indicator: ^3.0.0
  connectivity_plus: ^6.1.1
  image_cropper: ^8.1.0
  easy_localization: ^3.0.7
  flutter_markdown: ^0.7.4+3
  pointycastle: ^3.9.1
  hex: ^0.2.0
  accordion: ^2.6.0
  flutter_svg: ^2.0.16
  pinenacl: ^0.6.0
  fast_base58: ^0.2.1
  tutorial_coach_mark: ^1.2.12
  confetti: ^0.8.0
  url_launcher: ^6.3.1
  crypto: ^3.0.6
  screen_brightness: ^2.0.1
  uuid: ^4.5.1
  fade_and_translate: ^0.1.3
  markdown: ^7.2.2
  # durt2:
  #   path: ../../durt2
    # git:
    #   url: https://git.duniter.org/libs/durt2

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  icons_launcher: ^3.0.0
  build_runner: ^2.4.14
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/icon/gecko_flat.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

uses-material-design: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - config/
    - assets/
    - assets/translations/
    - assets/home/
    - assets/avatars/
    - assets/chests/
    - assets/icon/
    - assets/onBoarding/
    - assets/onBoarding/progress_bar/
    - assets/walletOptions/
    - sounds/
