import 'package:intl/date_symbols.dart';
import 'package:intl/date_symbol_data_custom.dart';

/// Register Esperanto date symbols in the intl package.
/// Must be called before any DateFormat usage with locale 'eo'.
void registerEsperantoDateSymbols() {
  initializeDateFormattingCustom(
    locale: 'eo',
    symbols: DateSymbols(
      NAME: 'eo',
      ERAS: ['aK', 'pK'],
      ERANAMES: ['antaŭ Kristo', 'post Kristo'],
      NARROWMONTHS: ['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D'],
      STANDALONENARROWMONTHS: ['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D'],
      MONTHS: [
        'januaro',
        'februaro',
        'marto',
        'aprilo',
        'majo',
        'junio',
        'julio',
        'aŭgusto',
        'septembro',
        'oktobro',
        'novembro',
        'decembro',
      ],
      STANDALONEMONTHS: [
        'januaro',
        'februaro',
        'marto',
        'aprilo',
        'majo',
        'junio',
        'julio',
        'aŭgusto',
        'septembro',
        'oktobro',
        'novembro',
        'decembro',
      ],
      SHORTMONTHS: ['jan', 'feb', 'mar', 'apr', 'maj', 'jun', 'jul', 'aŭg', 'sep', 'okt', 'nov', 'dec'],
      STANDALONESHORTMONTHS: ['jan', 'feb', 'mar', 'apr', 'maj', 'jun', 'jul', 'aŭg', 'sep', 'okt', 'nov', 'dec'],
      WEEKDAYS: ['dimanĉo', 'lundo', 'mardo', 'merkredo', 'ĵaŭdo', 'vendredo', 'sabato'],
      STANDALONEWEEKDAYS: ['dimanĉo', 'lundo', 'mardo', 'merkredo', 'ĵaŭdo', 'vendredo', 'sabato'],
      SHORTWEEKDAYS: ['di', 'lu', 'ma', 'me', 'ĵa', 've', 'sa'],
      STANDALONESHORTWEEKDAYS: ['di', 'lu', 'ma', 'me', 'ĵa', 've', 'sa'],
      NARROWWEEKDAYS: ['D', 'L', 'M', 'M', 'Ĵ', 'V', 'S'],
      STANDALONENARROWWEEKDAYS: ['D', 'L', 'M', 'M', 'Ĵ', 'V', 'S'],
      SHORTQUARTERS: ['T1', 'T2', 'T3', 'T4'],
      QUARTERS: ['1-a trimonato', '2-a trimonato', '3-a trimonato', '4-a trimonato'],
      AMPMS: ['atm', 'ptm'],
      DATEFORMATS: ['EEEE, d-\'a\' \'de\' MMMM y', 'y-MMMM-dd', 'y-MMM-dd', 'yy-MM-dd'],
      TIMEFORMATS: ['HH:mm:ss zzzz', 'HH:mm:ss z', 'HH:mm:ss', 'HH:mm'],
      DATETIMEFORMATS: ['{1} {0}', '{1} {0}', '{1} {0}', '{1} {0}'],
      FIRSTDAYOFWEEK: 0,
      WEEKENDRANGE: [5, 6],
      FIRSTWEEKCUTOFFDAY: 3,
    ),
    patterns: {
      'd': 'd',
      'E': 'ccc',
      'EEEE': 'cccc',
      'LLL': 'LLL',
      'LLLL': 'LLLL',
      'M': 'L',
      'Md': 'MM-dd',
      'MEd': 'MM-dd, EEE',
      'MMM': 'LLL',
      'MMMd': 'MMM d',
      'MMMEd': 'EEE d MMM',
      'MMMM': 'LLLL',
      'MMMMd': 'MMMM d',
      'MMMMEEEEd': 'EEEE d MMMM',
      'QQQ': 'QQQ',
      'QQQQ': 'QQQQ',
      'y': 'y',
      'yM': 'y-MM',
      'yMd': 'y-MM-dd',
      'yMEd': 'EEE, y-MM-dd',
      'yMMM': 'MMM y',
      'yMMMd': 'd MMM y',
      'yMMMEd': 'EEE, d MMM y',
      'yMMMM': 'MMMM y',
      'yMMMMd': 'd MMMM y',
      'yMMMMEEEEd': 'EEEE, d MMMM y',
      'yQQQ': 'QQQ y',
      'yQQQQ': 'QQQQ y',
      'H': 'HH',
      'Hm': 'HH:mm',
      'Hms': 'HH:mm:ss',
      'j': 'HH',
      'jm': 'HH:mm',
      'jms': 'HH:mm:ss',
      'jmv': 'HH:mm v',
      'jmz': 'HH:mm z',
      'jz': 'HH z',
      'm': 'mm',
      'ms': 'mm:ss',
      's': 'ss',
      'v': 'v',
      'z': 'z',
      'zzzz': 'zzzz',
      'ZZZZ': 'ZZZZ',
    },
  );
}
