[package]
name = "dubp_rs"
version = "0.1.0"
authors = ["Éloïs SANCHEZ <elois@duniter.org>"]
license = "AGPL-3.0"
edition = "2018"

[lib]
name = "dubp_rs"
crate-type = ["rlib"]

[dependencies]
allo-isolate = "0.1.6"
dup-crypto = { version = "0.45.0", features = ["bip32-ed25519", "dewif", "mnemonic", "mnemonic_french", "scrypt"] }
fast-threadpool = { version = "0.3.0", default-features = false }
once_cell = { version = "1.3.1", default-features = false, features = ["std"] }
parking_lot = "0.11.1"
thiserror = "1.0.24"

[build-dependencies]
cbindgen = "0.14.3"
dart-bindgen = "0.1.7"

[dev-dependencies]
assert_matches = "1.5.0"
