#!/bin/sh
# Pre-commit hook: auto-format only staged Dart files in lib/

# Get list of staged .dart files in lib/
STAGED_DART_FILES=$(git diff --cached --name-only --diff-filter=ACM -- 'lib/**.dart')

if [ -n "$STAGED_DART_FILES" ]; then
  dart format -l 120 $STAGED_DART_FILES
  echo "$STAGED_DART_FILES" | xargs git add
fi

exit 0
